-- V1__schema.sql
-- PostgreSQL

-- =========================
-- USERS
-- =========================
CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       email VARCHAR(255) NOT NULL UNIQUE,
                       password_hash VARCHAR(255) NOT NULL,
                       role VARCHAR(50) NOT NULL,
                       nome VARCHAR(255) NOT NULL,
                       cpf VARCHAR(11) NOT NULL UNIQUE,
                       celular VARCHAR(20),

                       CONSTRAINT ck_users_role
                           CHECK (role IN ('ADMIN', 'USER'))
);

CREATE INDEX idx_users_role ON users(role);

-- =========================
-- FILMES
-- =========================
CREATE TABLE filmes (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                        titulo VARCHAR(255) NOT NULL,
                        poster VARCHAR(500) NOT NULL,
                        backdrop VARCHAR(500) NOT NULL,

                        classificacao VARCHAR(50) NOT NULL,
                        duracao INT NOT NULL,

                        sinopse TEXT NOT NULL,

                        status VARCHAR(50) NOT NULL,

                        CONSTRAINT ck_filmes_status
                            CHECK (status IN ('EM_CARTAZ', 'EM_BREVE', 'ENCERRADO')),

                        CONSTRAINT ck_filmes_duracao
                            CHECK (duracao >= 0)
);

CREATE INDEX idx_filmes_status ON filmes(status);

-- =========================
-- ELEMENT COLLECTIONS DE FILME
-- =========================
CREATE TABLE filme_generos (
                               filme_id BIGINT NOT NULL,
                               genero VARCHAR(100) NOT NULL,

                               CONSTRAINT fk_filme_generos_filme
                                   FOREIGN KEY (filme_id) REFERENCES filmes(id)
                                       ON DELETE CASCADE,

                               CONSTRAINT pk_filme_generos
                                   PRIMARY KEY (filme_id, genero)
);

CREATE INDEX idx_filme_generos_genero ON filme_generos(genero);

CREATE TABLE filme_diretores (
                                 filme_id BIGINT NOT NULL,
                                 diretor VARCHAR(255) NOT NULL,

                                 CONSTRAINT fk_filme_diretores_filme
                                     FOREIGN KEY (filme_id) REFERENCES filmes(id)
                                         ON DELETE CASCADE,

                                 CONSTRAINT pk_filme_diretores
                                     PRIMARY KEY (filme_id, diretor)
);

CREATE INDEX idx_filme_diretores_diretor ON filme_diretores(diretor);

CREATE TABLE filme_elenco (
                              filme_id BIGINT NOT NULL,
                              ator VARCHAR(255) NOT NULL,

                              CONSTRAINT fk_filme_elenco_filme
                                  FOREIGN KEY (filme_id) REFERENCES filmes(id)
                                      ON DELETE CASCADE,

                              CONSTRAINT pk_filme_elenco
                                  PRIMARY KEY (filme_id, ator)
);

CREATE INDEX idx_filme_elenco_ator ON filme_elenco(ator);

-- =========================
-- SALAS
-- =========================
CREATE TABLE salas (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       nome VARCHAR(255) NOT NULL UNIQUE,
                       capacidade INT NOT NULL,

                       CONSTRAINT ck_salas_capacidade
                           CHECK (capacidade > 0)
);

CREATE INDEX idx_salas_nome ON salas(nome);

-- =========================
-- SESSOES
-- =========================
CREATE TABLE sessoes (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                         inicio TIMESTAMP NOT NULL,
                         tipo VARCHAR(255) NOT NULL,

                         filme_id BIGINT NOT NULL,
                         sala_id BIGINT NOT NULL,

                         CONSTRAINT fk_sessoes_filme
                             FOREIGN KEY (filme_id) REFERENCES filmes(id),

                         CONSTRAINT fk_sessoes_sala
                             FOREIGN KEY (sala_id) REFERENCES salas(id)
);

CREATE INDEX idx_sessoes_inicio ON sessoes(inicio);
CREATE INDEX idx_sessoes_filme_id ON sessoes(filme_id);
CREATE INDEX idx_sessoes_sala_id ON sessoes(sala_id);

-- Se você vai buscar por "data" (dia) com frequência, esse índice ajuda:
-- (equivalente ao seu endpoint GET /sessoes?data=YYYY-MM-DD)
CREATE INDEX idx_sessoes_data ON sessoes ((inicio::date));

-- =========================
-- ASSENTOS POR SESSAO
-- =========================
CREATE TABLE assentos_sessao (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                 sessao_id BIGINT NOT NULL,
                                 codigo VARCHAR(10) NOT NULL,
                                 ocupado BOOLEAN NOT NULL DEFAULT FALSE,

                                 CONSTRAINT fk_assentos_sessao_sessao
                                     FOREIGN KEY (sessao_id) REFERENCES sessoes(id)
                                         ON DELETE CASCADE,

                                 CONSTRAINT uk_assentos_sessao_codigo
                                     UNIQUE (sessao_id, codigo)
);

CREATE INDEX idx_assentos_sessao_sessao_id ON assentos_sessao(sessao_id);
CREATE INDEX idx_assentos_sessao_ocupado ON assentos_sessao(ocupado);